# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PinentryTouchid < Formula
  desc "Custom GPG pinentry program for macOS that allows using Touch ID for fetching the password from
the macOS keychain.
"
  homepage "https://github.com/jorgelbg/pinentry-touchid"
  version "0.0.2"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgelbg/pinentry-touchid/releases/download/v0.0.2/pinentry-touchid_0.0.2_macos_amd64.tar.gz"
      sha256 "573eb708fb9a69d0eea526c50b2703d4bcd42c94d6ecf57bf3661a6947d77123"
    end
  end

  depends_on "pinentry-mac"
  depends_on "pinentry"

  def install
    bin.install "pinentry-touchid"
  end

  def caveats; <<~EOS
    ✅ Add the following line to your ~/.gnupg/gpg-agent.conf file:
          pinentry-program #{bin}/pinentry-touchid

    ✅ Then reload your gpg-agent:
          gpg-connect-agent reloadagent /bye
  EOS
  end

  test do
    system "#{bin}/pinentry-touchid -check"
  end
end
