# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PinentryTouchid < Formula
  desc "Custom GPG pinentry program for macOS that allows using Touch ID for fetching the password from
the macOS keychain.
"
  homepage "https://github.com/jorgelbg/pinentry-touchid"
  version "0.0.3"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jorgelbg/pinentry-touchid/releases/download/v0.0.3/pinentry-touchid_0.0.3_macos_arm64.tar.gz"
      sha256 "6f1c24a02e836ce45eeae402785328a989e0aba64ab23ae3ed251d8269bd7772"

      def install
        bin.install "pinentry-touchid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jorgelbg/pinentry-touchid/releases/download/v0.0.3/pinentry-touchid_0.0.3_macos_amd64.tar.gz"
      sha256 "e96c5fe6c1db250fcd2301451e59ed831c4c4701ee11a5dddb6619607b484708"

      def install
        bin.install "pinentry-touchid"
      end
    end
  end

  depends_on "pinentry-mac"
  depends_on "pinentry"

  def caveats; <<~EOS
    ➡️  Ensure that pinentry-mac is the default pinentry program:
          #{bin}/pinentry-touchid -fix

    ✅  Add the following line to your ~/.gnupg/gpg-agent.conf file:
          pinentry-program #{bin}/pinentry-touchid

    🔄  Then reload your gpg-agent:
          gpg-connect-agent reloadagent /bye

    🔑  Run the following command to disable "Save in Keychain" in pinentry-mac:
          defaults write org.gpgtools.common DisableKeychain -bool yes

    ⛔️  If you are upgrading from a previous version, you will be asked to give
        access again to the keychain entry. Click "Always Allow" after the
        Touch ID verification to prevent this dialog from showing.
  EOS
  end
end
